export const CHANGE_INFO_REQUEST = "@CHANGE_INFO/CHANGE_INFO_REQUEST";
export const CHANGE_INFO_SUCCESS = "@CHANGE_INFO/CHANGE_INFO_RSUCCESS";
export const CHANGE_INFO_FAILED = "@CHANGE_INFO/CHANGE_INFO_FAILED";
